package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
@EnableWebMvc
public class Library {
  public static void main(String[] args) {
    SpringApplication.run(Library.class, args);
  }
}
